Clear cached shared object build on exit

diff --git a/docker/common/manylinux-build-wheels b/docker/common/manylinux-build-wheels
--- a/docker/common/manylinux-build-wheels
+++ b/docker/common/manylinux-build-wheels
@@ -33,8 +33,10 @@ mkdir -p "${WHEELS_DIR}"
 mkdir -p dist
 mkdir -p dist_full
 
-export FRANKY_LIB_CACHE_DIR="${FRANKY_LIB_CACHE_DIR:-$(pwd)/lib_cache}"
-mkdir -p "${FRANKY_LIB_CACHE_DIR}"
+# Share core library between builds, clean up after
+FRANKY_LIB_CACHE_DIR=$(mktemp -d)
+export FRANKY_LIB_CACHE_DIR
+trap 'rm -rf "${FRANKY_LIB_CACHE_DIR}"' EXIT
 
 # Compile wheels
 echo "Building wheels..."
